"""Stage 12: Export — Package everything into a ready-to-publish export pack."""

from __future__ import annotations

import json
import logging
import shutil
import zipfile
from pathlib import Path

from app.schemas import ExportPack, Script
from app.utils.paths import get_export_dir, get_final_video_path, get_job_dir

logger = logging.getLogger(__name__)


async def run(
    job_id: str,
    script: Script,
    video_path: str,
) -> ExportPack:
    """Create the export pack — everything needed to publish on Qoneqt.

    Export pack contains:
    - final.mp4 — the video
    - thumbnail.jpg — video thumbnail
    - caption.txt — post caption
    - hashtags.txt — hashtags
    - metadata.json — pipeline metadata
    - script.md — human-readable script
    """
    logger.info("[%s] Stage 12: Export — creating publish-ready pack", job_id)

    export_dir = get_export_dir(job_id)
    job_dir = get_job_dir(job_id)

    # 1. Copy final video
    video_export = export_dir / "final.mp4"
    if Path(video_path).exists():
        shutil.copy2(video_path, video_export)

    # 2. Generate thumbnail (first frame of video)
    thumbnail_path = export_dir / "thumbnail.jpg"
    try:
        from app.video.ffmpeg_utils import run_ffmpeg

        run_ffmpeg([
            "-y",
            "-i", str(video_path),
            "-vframes", "1",
            "-q:v", "2",
            str(thumbnail_path),
        ])
    except Exception as e:
        logger.warning("[%s] Thumbnail generation failed: %s", job_id, e)

    # 3. Write caption
    caption_path = export_dir / "caption.txt"
    with open(caption_path, "w", encoding="utf-8") as f:
        f.write(script.caption)

    # 4. Write hashtags
    hashtags_path = export_dir / "hashtags.txt"
    with open(hashtags_path, "w", encoding="utf-8") as f:
        f.write(" ".join(script.hashtags))

    # 5. Write metadata
    metadata = {
        "job_id": job_id,
        "title": script.title,
        "caption": script.caption,
        "hashtags": script.hashtags,
        "cta": script.cta,
        "facts_used": script.facts_used,
        "ai_generated": True,
        "disclosure": "This video was generated by AI using QoneqtForge.",
        "pipeline": "QoneqtForge v1.0",
    }
    metadata_path = export_dir / "metadata.json"
    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2, ensure_ascii=False)

    # 6. Write human-readable script
    script_md_path = export_dir / "script.md"
    with open(script_md_path, "w", encoding="utf-8") as f:
        f.write(f"# {script.title}\n\n")
        f.write(f"**Hook:** {script.hook}\n\n")
        for beat in script.beats:
            f.write(f"**[{beat.role.upper()}]** {beat.text}\n\n")
        f.write(f"\n**CTA:** {script.cta}\n\n")
        f.write(f"**Caption:** {script.caption}\n\n")
        f.write(f"**Hashtags:** {' '.join(script.hashtags)}\n")

    # 7. Create ZIP of export pack
    zip_path = job_dir / "export.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for file in export_dir.iterdir():
            if file.is_file():
                zf.write(file, file.name)

    logger.info("[%s] ✓ Export pack created: %s", job_id, zip_path.name)

    return ExportPack(
        video_path=str(video_export),
        thumbnail_path=str(thumbnail_path),
        caption=script.caption,
        hashtags=script.hashtags,
        metadata=metadata,
        script_md=script_md_path.read_text(encoding="utf-8"),
    )
