"""Image Router — fallback chain: Pollinations → Cloudflare → Pexels.

Always returns an image. The pipeline must NEVER hard-fail on a single scene.
"""

from __future__ import annotations

import logging
import random
from io import BytesIO
from typing import Any

from PIL import Image

from app.providers.base import ImageProvider, ProviderError
from app.providers.img_cloudflare import CloudflareImageProvider
from app.providers.img_pexels import PexelsProvider
from app.providers.img_pollinations import PollinationsProvider

logger = logging.getLogger(__name__)

DEFAULT_CHAIN: list[type[ImageProvider]] = [PollinationsProvider, CloudflareImageProvider, PexelsProvider]

_last_provider: str = "none"


def get_last_image_provider() -> str:
    """Get the name of the provider that served the last image."""
    return _last_provider


def resize_and_crop(image_bytes: bytes, target_width: int = 1080, target_height: int = 1920) -> bytes:
    """Resize and center-crop image to exact target dimensions."""
    img = Image.open(BytesIO(image_bytes))

    # Convert to RGB if necessary
    if img.mode != "RGB":
        img = img.convert("RGB")

    # Calculate scaling to cover the target (upscale to 1.25x for Ken Burns room)
    scale_factor = 1.25
    target_w = int(target_width * scale_factor)
    target_h = int(target_height * scale_factor)

    # Scale to cover
    w_ratio = target_w / img.width
    h_ratio = target_h / img.height
    scale = max(w_ratio, h_ratio)

    new_w = int(img.width * scale)
    new_h = int(img.height * scale)
    img = img.resize((new_w, new_h), Image.LANCZOS)

    # Center crop to target (with 1.25x for Ken Burns)
    left = (new_w - target_w) // 2
    top = (new_h - target_h) // 2
    img = img.crop((left, top, left + target_w, top + target_h))

    # Save to bytes
    output = BytesIO()
    img.save(output, format="PNG", quality=95)
    return output.getvalue()


async def generate_image(
    prompt: str,
    width: int = 1080,
    height: int = 1920,
    seed: int | None = None,
    style_prefix: str = "",
    stock_query: str | None = None,
    chain: list[type[ImageProvider]] | None = None,
    **kwargs: Any,
) -> tuple[bytes, str]:
    """Generate an image using the fallback chain.

    Returns:
        Tuple of (image_bytes, provider_name)
    """
    global _last_provider

    if seed is None:
        seed = random.randint(1, 999999)

    # Prepend style prefix to prompt
    full_prompt = f"{style_prefix}, {prompt}" if style_prefix else prompt

    providers = chain or DEFAULT_CHAIN
    last_error = None

    for ProviderClass in providers:
        provider = ProviderClass()

        if not await provider.is_available():
            logger.info("Image provider %s not available, skipping", provider.name)
            continue

        # For Pexels, use stock_query if available
        extra_kwargs = {}
        if provider.name == "pexels" and stock_query:
            extra_kwargs["stock_query"] = stock_query

        # Try twice with different seeds
        for attempt in range(2):
            try:
                current_seed = seed + attempt * 1000
                image_bytes = await provider.generate(
                    prompt=full_prompt,
                    width=width,
                    height=height,
                    seed=current_seed,
                    **extra_kwargs,
                )

                # Resize and crop to exact dimensions
                processed = resize_and_crop(image_bytes, width, height)

                _last_provider = provider.name
                logger.info("✓ Image generated by %s (attempt %d)", provider.name, attempt + 1)
                return processed, provider.name

            except Exception as e:
                logger.warning(
                    "Image provider %s attempt %d failed: %s",
                    provider.name,
                    attempt + 1,
                    e,
                )
                last_error = e
                continue

    raise ProviderError(f"All image providers failed. Last error: {last_error}")
